#!/usr/bin/env perl

use strict;
use warnings;

my $seq = 'TACGCTCTAACCTCTAACCTCTAACGCCTCTAACTGGCGCACTCTAACACTCTAACCTCTAACCTCTAACCTCTAACCTCTAACCTCTAACCAAGAGCTCTAACTGCCTCTAACGCAACTCTAACCGCTGCGGCTCTAACCCTCTAACCTCTAACCTCTAACGACTCTAACCCTTCCTCTAACCAAGCTCTAACTCCTTCGTACCTCTAACCTCTAACTCTCTAACCTCCAAGATGCTCTAACTCTCTAACACTCTAACCTCTAACCTGCGCTCTAACCAGCTCGCTCTAACTCCCTCTAACGCTCTAACCTCTAACGACTCTAACTCTCTCTAACGATGCTCTAACCTACCTCTAACCTCTAACTCTCTAACTCCCGTTTGCTCTAACACTCTCTAACGAACTCTAACCTCTAACCTCTAACTAGTAGGAAGCTCTAACCTCTAACCTCTAACAGTGTCTCTAACAATCTCTCTAACCTCTAACGGCTCTAACACTCTAACAGAGGGTCTCTAACCCCGTGACCTCTAACCACCTCTAACTCTCTAACCTCTAACGCTCTAACCTCTAACATGATCCTCTAACGGTCTCTAACACACTCTAACCACCCTCTCTAACAATTAACTCTAACCCTCTAACCTCTAACCGCTCTAACGCGCCCCTCTAACGATGAACAGCCCTCTAACGCCTCTAACTGTATCTCTAACTTAGAAGCTCTAACAATGTAACCTCTAACCCTCTAACATCTCTAACCTCCTCTAACTGCTCTCTAACCTCTAACGCTCTAACGTCTCTAACAGGCTCTAACACCCACGGTCTCTAACGATAGCCCTCTAACAACCCAATAGCTCTAACAGTTTCGGGGAGCTCTAACCTCTAACCTCTAACAACTCTAACACTCTAACCACTCTAACCTCTAACAACTCTAACTGGGCCTCTAACGGGGTGCTCTAACACTCTAACCGGCTCTAACCCTCTAACCTCTAACCTCTAAC';

my $motif = 'CTCTAACCT';

my $sl = length($seq);
my $ml = length($motif);

for (my $i = 0; $i < $sl; ++$i){
   my $s = substr($seq, $i, $ml);
   if ($s eq $motif){
      my $p = $i + 1;
      print "$p ";
   }
}
print "\n";

exit(0);

